### ISSUE TITLE
Some music channels ignore the volume setting

### ISSUE THREAD

**Issue by Interrupt** [Interrupt/systemshock#210]
The way we're setting music volume right now seems to ignore the master music volume sometimes.
You can see this on the title screen by trying to set the volume to 0 at `setup.c: 1503`

A better way of setting the music volume might be to manually adjust the values being streamed into SDL in the callback, until the bug affecting SDL_Mixer's music volume setting on Windows is fixed.

**Comment by donnierussellii** [comment]
I tried varying the volume this way. The sound very audibly pops at various times: when the game starts (several random loud pops), when you're moving the volume slider, or anytime the volume changes in general. I couldn't figure out what I was doing wrong, so gave it up.

But the title and credits music are not obeying the music volume setting. Fixed in a PR.

**Comment by Interrupt** [comment]
Maybe we should be using SDL_Mixer's music volume function then, and lean on them to fix the library rather than trying to work around it?

**Comment by donnierussellii** [comment]
Yes, that function seems to help tremendously! Working on commits...
