### ISSUE TITLE
Strange colors

### ISSUE THREAD

**Issue by acd2001** [Interrupt/systemshock#261]
I compile latest source and color & gamma in game are strange.
I don't use OpenGL, i compile in software mode.
I include some pictures.

![immagine1](https://user-images.githubusercontent.com/43091220/47250467-c346b380-d421-11e8-950a-d370eeefde6d.JPG)
![immagine2](https://user-images.githubusercontent.com/43091220/47250468-c3df4a00-d421-11e8-9bff-231e73b46c45.JPG)
![immagine3](https://user-images.githubusercontent.com/43091220/47250469-c477e080-d421-11e8-9755-0d03d3ae72bd.JPG)

Only with gamma at max is normal. Colors are very saturated

![immagine4](https://user-images.githubusercontent.com/43091220/47250470-c477e080-d421-11e8-92d6-8d1a2bb8cb80.JPG)

**Comment by donnierussellii** [comment]
The screenshot shows that OpenGL driver isn't used. That does its own gamma correction, as I recently learned, so we need to add some correction level to make up the difference.

**Comment by donnierussellii** [comment]
Fix in my PR #263

**Comment by Kappa971** [comment]
This is still a problem with Shockolate compiled with OpenGL support and the "shaders" folder where the executable is located.
Removing the "shaders" folder seems to remove OpenGL support and gamma works fine.
With the "shaders" folder present, both the Software render and OpenGL have too dark gamma, you need to increase it to maximum to get good colors. Also it's impossible to play in OpenGL because even increasing the gamma to maximum, you can't see anything in the shadows (contrary to the Software/original renderer).
