### ISSUE TITLE
Decide on a code formatting style

### ISSUE THREAD

**Issue by Interrupt** [Interrupt/systemshock#32]
Should we leave the formatting for code as is, for historical purposes? Should we run a formatter against everything to unify the formatting? I'm torn on this one.

**Comment by winterheart** [comment]
There no common formatting in code. 3 spaces indentation, 1 space, tabs, curls on next line, on same line... This distract attention from code.

I suggest to use clang-format with llvm style with two exceptions:
* ColumnLimit: 120
* AlignEscapedNewlines: Left (because some macros would look weird with 120 columns)

**Comment by Interrupt** [comment]
Okay, lets do it. I'd also throw in a vote for four spaces to indent.

**Comment by winterheart** [comment]
Added PR. Be careful through. It can't handle with ASM inlines and some quirky format styles that appears in code.
