### ISSUE TITLE
Shockolate window starts at this size and when i maximized the window is displayed black

### ISSUE THREAD

**Issue by PoisoN-Dieg0** [Interrupt/systemshock#364]
This problem has never happened to me and I am just experiencing it. the case is, when I start Shockolate the window of this size starts and it is displayed black. I have tried to restart my PC and redownload the port but the problem continues.
![image](https://user-images.githubusercontent.com/64511619/80556204-d9331e00-89a0-11ea-94d9-8d668b5f2445.png)
![image](https://user-images.githubusercontent.com/64511619/80556191-d1737980-89a0-11ea-88e2-d30a3ed23f49.png)

**Comment by donnierussellii** [comment]
The exe's modified date says the version (0.7.7) is from last year. Try backing up then deleting your prefs.txt file (found in YOURWINDRIVE:\Users\YOURUSERNAME\AppData\Roaming\Interrupt\SystemShock ), then running the exe again.

Maybe there was a bug in 0.7.7 that was fixed in the current version 0.8.2. The SDL version has also been updated.

**Comment by PoisoN-Dieg0** [comment]
> The exe's modified date says the version (0.7.7) is from last year. Try backing up then deleting your prefs.txt file (found in YOURWINDRIVE:\Users\YOURUSERNAME\AppData\Roaming\Interrupt\SystemShock ), then running the exe again.
> 
> Maybe there was a bug in 0.7.7 that was fixed in the current version 0.8.2. The SDL version has also been updated.

Thanks, it works.
