### ISSUE TITLE
OpenGL render is completely black

### ISSUE THREAD

**Issue by jjbarr** [Interrupt/systemshock#367]
If I render with OpenGL, the 3d viewport doesn't render at all: it's just black.

I am running on ArchLinux, with Mesa 20 and an AMD Radeon 5600.

**Comment by jjbarr** [comment]
This can be fixed by placing the frag and vert shaders in the correct location in your gamedir.

**Comment by Gerwin2k** [comment]
Sorry for reviving 
I am a new Linux user and also have a black OpenHL rendering view, only the HUD is drawn. 

"This can be fixed by placing the frag and vert shaders in the correct location in your gamedir."
I tried this, regardless of it lacking specifics in the suggestion, and it failed to resolve things. Please advise.

**Comment by jjbarr** [comment]
Sorry for responding so late, but what you need to do is put the contents of the `shaders` folder in the repo (*.frag, *.vert) into the root folder of your shockolate install (whereever the `res` folder is).

**Comment by Gerwin2k** [comment]
Thanks, that is very clear. 
Unfortuntaly I already tried exactly that, and just tried it again, to no avail.  Actually I am pretty sure the game can find these four shader files just fine, because it is only when I temporarely remove the ./shaders folder the whole OpenGL option gets removed from the in-game options dialog.  

I will stick to the Win 32 version for the time being, which runs just fine. 

For anyone interested here is the log as copied from the terminal:
[Linux x64 solus 4.1 mate log.txt](https://github.com/Interrupt/systemshock/files/4991327/Linux.x64.solus.4.1.mate.log.txt)
Note that I did not build the libs as is suggested in an included .sh file, but installed the necessary libs with the OS software center. The game resides in "/home/*myname*/Games/SShock"
