### ISSUE TITLE
Trying to build on Rpi4/Retropie but exits with error.

### ISSUE THREAD

**Issue by ectorhga** [Interrupt/systemshock#371]
Hi,

I try to compile Systemshock on a Raspberry Pi 4 based on a Retropie (4.6) image. The compilation fails with the following error in the `make systemshock` part:

![image](https://user-images.githubusercontent.com/56919853/82741809-5d858080-9d56-11ea-9f87-6192900c90fd.png)

I hope this is the right place to ask for help! Thanks!

**Comment by donnierussellii** [comment]
parm_ptr is of type va_list . va_list is being treated as a pointer type here, to access variables on the stack by adding an int offset. The problem is that va_list is really a "handle" type used only with va_start, va_arg and va_end . Using va_arg gives us the value of each argument in succession.

Maybe to fix this we could set up a buffer, pointed to by parm_ptr, filled by va_arg. We would need to know how much data to get.

**Comment by Interrupt** [comment]
Could you try building off of this new PR and see if it fixes your build?
https://github.com/Interrupt/systemshock/pull/372

**Comment by ectorhga** [comment]
I must admit that I don't know enough of github to just download this PR, but I was able to download the file and replace it manually.

The game compiles now without error and when I use the system's own SDL library I can start and run the game! Great success! Although 1024x768 is still a bit much for the pi, but 640x480 is quite fluent. Btw is there a way to change to other resolutions?

Anyways thanks for your help!
