### ISSUE TITLE
add missing hotkeys

### ISSUE THREAD

**Issue by arxo** [Interrupt/systemshock#375]
The readme mentions several hotkeys as missing, but I could not find an issue ticket for this:
-     F1..F10 for the side MFD's
-     0..9 for the Hacker's hardware
 
Any background on why these are missing?
In the DOS version I used especially the F-keys a lot...

**Comment by donnierussellii** [comment]
The 0-9 hotkeys are not missing; they are included in Prefs.c, where keybinds are handled.

The following calls should get the function keys working:
  hotkey_add(KEY_F1, DEMO_CONTEXT,mfd_button_callback_kb,0);
  hotkey_add(KEY_F2, DEMO_CONTEXT,mfd_button_callback_kb,1);
  hotkey_add(KEY_F3, DEMO_CONTEXT,mfd_button_callback_kb,2);
  hotkey_add(KEY_F4, DEMO_CONTEXT,mfd_button_callback_kb,3);
  hotkey_add(KEY_F5, DEMO_CONTEXT,mfd_button_callback_kb,4);
  hotkey_add(KEY_F6, DEMO_CONTEXT,mfd_button_callback_kb,5);
  hotkey_add(KEY_F7, DEMO_CONTEXT,mfd_button_callback_kb,6);
  hotkey_add(KEY_F8, DEMO_CONTEXT,mfd_button_callback_kb,7);
  hotkey_add(KEY_F9, DEMO_CONTEXT,mfd_button_callback_kb,8);
  hotkey_add(KEY_F10,DEMO_CONTEXT,mfd_button_callback_kb,9);
But these should be integrated into the keybinds system.

There are hotkey_add() calls throughout the source, but they are commented out so that everything is handled in Prefs.c. The F1-F10 hotkey_add() calls above were commented out at some point before I implemented keybinds, maybe because they weren't needed in the Mac port? I don't know; I also don't know if the hotkey_add() calls above actually work.

**Comment by arxo** [comment]
I tried to have a go at this myself and at least the MFD hotkeys F1-F10 are now working.

Here's a diff vs. bb31626db603eac6ade442298340a6c8574cc9c0:


diff --git a/src/GameSrc/newmfd.c b/src/GameSrc/newmfd.c
index 51f9aae1..8c44c259 100644
--- a/src/GameSrc/newmfd.c
+++ b/src/GameSrc/newmfd.c
@@ -962,17 +962,17 @@ uchar mfd_button_callback_kb(ushort keycode, uint32_t context, intptr_t data) {
     int fkeynum;
 
     if (!global_fullmap->cyber) {
-        fkeynum = (int)context; // dummy funcs
-        fkeynum = (int)keycode;
 
-        fkeynum = (int)data;
+        fkeynum = (int)keycode - 128;
 
-        if (fkeynum >= MFD_NUM_VIRTUAL_SLOTS)
+        if (fkeynum >= MFD_NUM_VIRTUAL_SLOTS) {
             which_panel = MFD_RIGHT;
-        else
+        }
+        else {
             which_panel = MFD_LEFT;
+        }
 
-        which_button = ((int)data) % MFD_NUM_VIRTUAL_SLOTS;
+        which_button = ((int)fkeynum) % MFD_NUM_VIRTUAL_SLOTS;
 
         mfd_select_button(which_panel, which_button);
     }
diff --git a/src/Libraries/H/keydefs.h b/src/Libraries/H/keydefs.h
index 460cc93a..bc0c39f0 100644
--- a/src/Libraries/H/keydefs.h
+++ b/src/Libraries/H/keydefs.h
@@ -32,18 +32,18 @@ along with this program.  If not, see <http://www.gnu.org/licenses/>.
 #define KEY_PAUSE	0x1b
 #define KEY_SPACE	0x20
 
-#define KEY_F1			0x10			// ¥¥¥Find out what these are
-#define KEY_F2			0x10
-#define KEY_F3			0x10
-#define KEY_F4			0x10
-#define KEY_F5			0x10
-#define KEY_F6			0x10
-#define KEY_F7			0x10
-#define KEY_F8			0x10
-#define KEY_F9			0x10
-#define KEY_F10		0x10
-#define KEY_F11		0x10
-#define KEY_F12		0x10
-#define KEY_F13		0x10
-#define KEY_F14		0x10
-#define KEY_F15		0x10
+#define KEY_F1			128 + 0
+#define KEY_F2			128 + 1
+#define KEY_F3			128 + 2
+#define KEY_F4			128 + 3
+#define KEY_F5			128 + 4
+#define KEY_F6			128 + 5
+#define KEY_F7		    128 + 6
+#define KEY_F8			128 + 7
+#define KEY_F9		    128 + 8
+#define KEY_F10		    128 + 9
+#define KEY_F11		    128 + 10
+#define KEY_F12		    128 + 11
+#define KEY_F13		    128 + 12
+#define KEY_F14		    128 + 13
+#define KEY_F15		    128 + 14
diff --git a/src/MacSrc/Prefs.c b/src/MacSrc/Prefs.c
index fe0a4272..832312b2 100644
--- a/src/MacSrc/Prefs.c
+++ b/src/MacSrc/Prefs.c
@@ -38,6 +38,8 @@ along with this program.  If not, see <http://www.gnu.org/licenses/>.
 #include "mainloop.h"
 #include "movekeys.h"
 
+extern uchar mfd_button_callback_kb(ushort keycode, uint32_t context, intptr_t data);
+
 //--------------------
 //  Filenames
 //--------------------
@@ -548,6 +550,16 @@ HOTKEYLOOKUP HotKeyLookup[] = {
     {"\"use_drug\"", DEMO_CONTEXT, use_drug_hotkey, 0, 0, ALT(';'), 0},
     {"\"hud_color\"", DEMO_CONTEXT, hud_color_bank_cycle, 0, 0, ALT('h'), 0},
     {"\"showhelp\"", DEMO_CONTEXT, olh_overlay_func, (intptr_t)&olh_overlay_on, 0, ALT('o'), 0},
+    {"\"mfd left 1\"", DEMO_CONTEXT, mfd_button_callback_kb, 0, 0, KEY_F1, 0},
+    {"\"mfd left 2\"", DEMO_CONTEXT, mfd_button_callback_kb, 0, 0, KEY_F2, 0},
+    {"\"mfd left 3\"", DEMO_CONTEXT, mfd_button_callback_kb, 0, 0, KEY_F3, 0},
+    {"\"mfd left 4\"", DEMO_CONTEXT, mfd_button_callback_kb, 0, 0, KEY_F4, 0},
+    {"\"mfd left 5\"", DEMO_CONTEXT, mfd_button_callback_kb, 0, 0, KEY_F5, 0},
+    {"\"mfd right 1\"", DEMO_CONTEXT, mfd_button_callback_kb, 0, 0, KEY_F6, 0},
+    {"\"mfd right 2\"", DEMO_CONTEXT, mfd_button_callback_kb, 0, 0, KEY_F7, 0},
+    {"\"mfd right 3\"", DEMO_CONTEXT, mfd_button_callback_kb, 0, 0, KEY_F8, 0},
+    {"\"mfd right 4\"", DEMO_CONTEXT, mfd_button_callback_kb, 0, 0, KEY_F9, 0},
+    {"\"mfd right 5\"", DEMO_CONTEXT, mfd_button_callback_kb, 0, 0, KEY_F10, 0},
     {"\"keypad 0\"", DEMO_CONTEXT, keypad_hotkey_func, 0, 0, DOWN('0'), 0},
     {"\"keypad 1\"", DEMO_CONTEXT, keypad_hotkey_func, 0, 0, DOWN('1'), 0},
     {"\"keypad 2\"", DEMO_CONTEXT, keypad_hotkey_func, 0, 0, DOWN('2'), 0},

**Comment by arxo** [comment]
my PR #377 was merged, so what's left are the  0..9 keys (and I forgot to update README.md ;)

**Comment by arxo** [comment]
remaining hotkeys added via PR #380
