### ISSUE TITLE
Splash screens should fade in/out

### ISSUE THREAD

**Issue by winterheart** [Interrupt/systemshock#55]
According to code (DrawSplashScreen() in [src/GameSrc/init.c](https://github.com/Interrupt/systemshock/blob/46adee1e9fbe288c98b3d56be1d28622c7deaac2/src/GameSrc/init.c#L499)) splash screens (Origin, LGS, SystemShock title) should fade in / fade out with palfx_start_fade_up()/finish_pal_effect().

**Comment by Interrupt** [comment]
The `draw_full_res_bm` function in `tools.c` that the splash screens are drawing with has code to call those functions, but it crashes on the `palfx_start_fade_up` line due to it trying to use memory that it already gave away. By keeping ahold of those bytes it doesn't crash, but it doesn't seem to do the fade up either, even when I explicitly call the `advance_pal_fx` functions. Going to need more digging to get this to work.
